sudo: required
dist: trusty

jobs:
 include:
    - stage: backend
      name: "backend tests"
      language: java
      jdk: oraclejdk8    
      before_script:
        - cd backend
        - chmod +x mvnw
      script:
        - ./mvnw clean test -B
        
    - stage: backend
      name: "backend test and build"
      language: java
      jdk: oraclejdk8
      env:
        global:
          - CC_TEST_REPORTER_ID=7df9353e2bc03f7e8a491e8d59cfaca8018610963a7d416a25be87a9e21cc6a4
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
        - cd backend
        - chmod +x mvnw
      script:
        - ./mvnw clean install -B
      after_script:
        - cd ..
        - ./cc-test-reporter format-coverage -d -t jacoco ./backend/target/jacoco-ut/jacoco.xml
        - ./cc-test-reporter upload-coverage -d -r 7df9353e2bc03f7e8a491e8d59cfaca8018610963a7d416a25be87a9e21cc6a4

    - stage: frontend
      name: "frontend build"
      language: node_js
      node_js:
        - 10.15.3
      before_script:
        - cd frondend/spark
        - npm install -g @angular/cli
        - npm install --save-dev @angular-devkit/build-angular
      script:
        - ng build

 notifications:
  email: false